### ISSUE TITLE
在微信内置浏览器中不好用[大哭]

### ISSUE THREAD

**Issue by yufeng217** [iazrael/xback#1]
先点个赞！
在手机web浏览器中都好用。
但是在微信内置浏览器中就不好用了，求解决方案~ [抱拳]

**Comment by iazrael** [comment]
不好意思, 没有做过微信的web页面, 可能微信自己修改过webview的历史记录, 导致这个判断不准, 但是暂时我没有时间研究这个, 你可以通过监听hashchange或者onpopstate看看在微信里的历史记录是否是正常的.
